const money=(n,d=2)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:d,maximumFractionDigits:d}).format(Number(n||0));
const num=n=>new Intl.NumberFormat('en-US').format(Number(n||0));
const pct=n=>`${Number(n||0).toFixed(1)}%`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const short=v=>String(v||'').length>18?`${String(v).slice(0,9)}…${String(v).slice(-6)}`:String(v||'');
const timeAgo=m=>m<1?'just now':m<60?`${m}m ago`:m<1440?`${Math.floor(m/60)}h ago`:`${Math.floor(m/1440)}d ago`;
const stamp=m=>new Date(Date.now()-m*60000).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const statusTone=s=>/fail|mismatch|rejected|exception|review|stuck|reversed/i.test(s)?'failed':/pending|processing|open|settling|submitted|partial|awaiting/i.test(s)?'pending':/active|owned|verified|confirmed|complete|settled|accepted|matched|paid|qualified|approved|closed/i.test(s)?'success':'info';
const railClass=r=>String(r||'internal').toLowerCase().replace(/[^a-z]/g,'');

const users=[
{id:'usr_01HZX2',name:'Maya Chen',handle:'@maya',wallet:'0x7A4F…92C1',cash:842.16,usdc:1250,credits:430,stocks:378.42,stockCost:332.10,inventory:2,vaultValue:996,pending:694.4},
{id:'usr_01HZX9',name:'Andre Lewis',handle:'@andre',wallet:'0xA930…118D',cash:194.50,usdc:0,credits:4915,stocks:1234.18,stockCost:1018.45,inventory:5,vaultValue:2620,pending:1535.1},
{id:'usr_01HZYA',name:'Sofia Patel',handle:'@sofia',wallet:'0x4C11…E0A8',cash:55.22,usdc:480.25,credits:1319,stocks:0,stockCost:0,inventory:1,vaultValue:128,pending:89.6},
{id:'usr_01HZYQ',name:'Noah Kim',handle:'@noah',wallet:'0xD033…77A2',cash:2231.01,usdc:72.90,credits:850,stocks:521.37,stockCost:489.11,inventory:3,vaultValue:1118,pending:730.8},
{id:'usr_01HZZ4',name:'Ari Brooks',handle:'@ari',wallet:'0x88BE…1431',cash:18.46,usdc:902.44,credits:620,stocks:86.12,stockCost:95,inventory:0,vaultValue:0,pending:0},
{id:'usr_01J001',name:'Leo Park',handle:'@leo',wallet:'0x51F2…66B4',cash:711.90,usdc:150,credits:2033,stocks:694.31,stockCost:620,inventory:4,vaultValue:1485,pending:962.5}
];
const userById=Object.fromEntries(users.map(u=>[u.id,u]));
const userName=id=>userById[id]?.name||id||'System';

const positions={
usr_01HZX2:[['AAPL',1.21,268.20,243.10],['NVDA',0.44,110.22,89]],
usr_01HZX9:[['NVDA',3.20,727.04,590],['AAPL',1.86,412.74,356],['TSLA',0.27,94.40,72.45]],
usr_01HZYA:[],
usr_01HZYQ:[['TSLA',1.478,521.37,489.11]],
usr_01HZZ4:[['AAPL',0.39,86.12,95]],
usr_01J001:[['NVDA',2.05,465.92,410],['AAPL',1.03,228.39,210]]
};

const activities=[
{id:'evt_01',mins:0,type:'Stock sell filled',category:'Stocks',user:'usr_01HZX9',asset:'NVDA · 0.132 sh',ref:'ord_STK_8821',corr:'corr_stock_8821',amount:31.74,rail:'On-chain',status:'Confirmed',fee:.0128,note:'Owned NVDA was sold. Principal came from the user position; sale proceeds were credited to Cash.'},
{id:'evt_02',mins:1,type:'Stock sell fee recovered',category:'Fees',user:'usr_01HZX9',asset:'NVDA execution fee',ref:'fee_44329',corr:'corr_stock_8821',amount:-.20,rail:'Cash',status:'Settled',fee:0,note:'Configured user fee was collected against the execution/network cost.'},
{id:'evt_03',mins:2,type:'Offer accepted',category:'Marketplace',user:'usr_01HZYQ',counterparty:'usr_01HZX2',asset:'Air Jordan 1 Chicago',ref:'off_11983',corr:'corr_sale_11983',amount:412,rail:'Cash',status:'Settling',fee:0,note:'Seller accepted the buyer offer. Settlement chain continues under the same correlation ID.'},
{id:'evt_04',mins:3,type:'Buyer funds debited',category:'Marketplace',user:'usr_01HZX2',counterparty:'usr_01HZYQ',asset:'Air Jordan 1 Chicago',ref:'pay_11983',corr:'corr_sale_11983',amount:-412,rail:'Cash',status:'Confirmed',fee:0,note:'Buyer cash balance reserved and debited.'},
{id:'evt_05',mins:3,type:'Marketplace fee collected',category:'Treasury',user:'usr_01HZYQ',asset:'Air Jordan 1 Chicago',ref:'mfee_11983',corr:'corr_sale_11983',amount:4.12,rail:'Cash',status:'Confirmed',fee:0,note:'Only Chosen fee share is company revenue; gross sale value is not.'},
{id:'evt_06',mins:4,type:'Seller proceeds credited',category:'Marketplace',user:'usr_01HZYQ',asset:'Air Jordan 1 Chicago',ref:'sale_11983',corr:'corr_sale_11983',amount:407.88,rail:'Cash',status:'Settled',fee:0,note:'Net proceeds after marketplace fee credited to seller.'},
{id:'evt_07',mins:4,type:'Ownership transferred',category:'Vault',user:'usr_01HZX2',counterparty:'usr_01HZYQ',asset:'Air Jordan 1 Chicago',ref:'itm_00921',corr:'corr_sale_11983',amount:430,rail:'Internal',status:'Owned',fee:0,note:'Vault ownership moved from seller to buyer and listing closed.'},
{id:'evt_08',mins:5,type:'USDC crate purchase',category:'Purchases',user:'usr_01HZYA',asset:'Streetwear 100',ref:'pur_72119',corr:'corr_crate_72119',amount:-100,rail:'USDC',status:'Confirmed',fee:.0007,note:'USDC-funded crate. Original funding rail is preserved through later cashout.'},
{id:'evt_09',mins:5,type:'Crate Bonus issued',category:'Rewards',user:'usr_01HZYA',asset:'Streetwear 100',ref:'bonus_72119',corr:'corr_crate_72119',amount:5,rail:'Credits',status:'Confirmed',fee:0,note:'5% non-cash Crate Bonus issued separately from any outcome settlement.'},
{id:'evt_10',mins:6,type:'Reveal commitment created',category:'Reveals',user:'usr_01HZYA',asset:'Streetwear 100',ref:'rev_55102',corr:'corr_crate_72119',amount:0,rail:'Internal',status:'Confirmed',fee:0,note:'All outcomes were locked and hashed before user selection.'},
{id:'evt_11',mins:7,type:'Reveal completed',category:'Reveals',user:'usr_01HZYA',asset:'Supreme Box Logo Tee',ref:'rev_55102',corr:'corr_crate_72119',amount:128,rail:'Internal',status:'Verified',fee:0,note:'Fairness verification passed and reveal FMV was captured.'},
{id:'evt_12',mins:8,type:'Item kept in vault',category:'Vault',user:'usr_01HZYA',asset:'Supreme Box Logo Tee',ref:'itm_77201',corr:'corr_crate_72119',amount:128,rail:'Internal',status:'Owned',fee:0,note:'Initial FMV, original USDC funding rail and 365-day clock attached to item.'},
{id:'evt_13',mins:10,type:'Stock pack purchased',category:'Purchases',user:'usr_01HZX9',asset:'Equity Pack 50',ref:'pur_72118',corr:'corr_stockpack_72118',amount:-50,rail:'Cash',status:'Confirmed',fee:0,note:'Stock packs are cash-only.'},
{id:'evt_14',mins:11,type:'Stock buy submitted',category:'Stocks',user:'usr_01HZX9',asset:'AAPL',ref:'ord_STK_8818',corr:'corr_stockpack_72118',amount:49.86,rail:'On-chain',status:'Processing',fee:.0016,note:'Platform purchase order submitted after the reveal.'},
{id:'evt_15',mins:12,type:'Stock buy filled',category:'Stocks',user:'usr_01HZX9',asset:'AAPL · 0.209 sh',ref:'ord_STK_8818',corr:'corr_stockpack_72118',amount:49.86,rail:'On-chain',status:'Confirmed',fee:.0016,note:'Fill price and shares acquired captured.'},
{id:'evt_16',mins:12,type:'Stock lot assigned',category:'Stocks',user:'usr_01HZX9',asset:'AAPL · 0.209 sh',ref:'lot_55218',corr:'corr_stockpack_72118',amount:49.86,rail:'Internal',status:'Owned',fee:0,note:'Stock principal now belongs to the user portfolio.'},
{id:'evt_17',mins:14,type:'Cash cashback settled',category:'Vault',user:'usr_01J001',asset:'Sneaker 100 · Travis Scott',ref:'cb_09331',corr:'corr_crate_72111',amount:78,rail:'Cash',status:'Settled',fee:.0032,note:'Cash-funded crate settled back into Cash.'},
{id:'evt_18',mins:17,type:'Offer sent',category:'Marketplace',user:'usr_01HZX2',counterparty:'usr_01HZYQ',asset:'Air Jordan 1 Chicago',ref:'off_11982',corr:'corr_offer_11982',amount:395,rail:'Cash',status:'Open',fee:0,note:'Offer created and buyer funds reserved according to marketplace rules.'},
{id:'evt_19',mins:19,type:'Item transfer completed',category:'Vault',user:'usr_01J001',counterparty:'usr_01HZX2',asset:'New Balance 990v6',ref:'xfr_00221',corr:'corr_transfer_221',amount:220,rail:'Internal',status:'Confirmed',fee:.0011,note:'Sender and recipient ownership histories were updated.'},
{id:'evt_20',mins:20,type:'Transfer network fee',category:'Fees',user:'usr_01J001',asset:'New Balance 990v6 transfer',ref:'0xtransfer221',corr:'corr_transfer_221',amount:0,rail:'On-chain',status:'Confirmed',fee:.0011,note:'Actual network cost incurred for transfer.'},
{id:'evt_21',mins:22,type:'Reveal exception',category:'Reveals',user:'usr_01HZZ4',asset:'Equity Pack 100',ref:'rev_55099',corr:'corr_stockpack_72116',amount:0,rail:'Internal',status:'Review',fee:0,note:'Price quote exceeded freshness threshold. Assignment paused.'},
{id:'evt_22',mins:28,type:'USDC cashback settled',category:'Vault',user:'usr_01HZZ4',asset:'Streetwear 50',ref:'cb_09328',corr:'corr_crate_72115',amount:39.50,rail:'USDC',status:'Settled',fee:.0007,note:'USDC funding rail preserved.'},
{id:'evt_23',mins:34,type:'Offer declined',category:'Marketplace',user:'usr_01HZYQ',counterparty:'usr_01HZX9',asset:'Nike SB Dunk Jarritos',ref:'off_11977',corr:'corr_offer_11977',amount:460,rail:'Cash',status:'Closed',fee:0,note:'Seller declined. Buyer reserve was released.'},
{id:'evt_24',mins:39,type:'Cash crate purchase',category:'Purchases',user:'usr_01HZYQ',asset:'Sneaker 250',ref:'pur_72114',corr:'corr_crate_72114',amount:-250,rail:'Cash',status:'Confirmed',fee:0,note:'Cash-funded sneaker crate.'},
{id:'evt_25',mins:41,type:'Pity threshold triggered',category:'Reveals',user:'usr_01HZYQ',asset:'Sneaker 250',ref:'rev_55097',corr:'corr_crate_72114',amount:0,rail:'Internal',status:'Confirmed',fee:0,note:'Configured rarity protection affected the locked outcome set and was logged.'},
{id:'evt_26',mins:46,type:'Listing created',category:'Marketplace',user:'usr_01HZX2',asset:'Nike SB Dunk Jarritos',ref:'lst_10892',corr:'corr_item_77233',amount:510,rail:'Internal',status:'Active',fee:0,note:'Vault item moved from offer-only to fixed-price listing.'},
{id:'evt_27',mins:52,type:'Listing price removed',category:'Marketplace',user:'usr_01HZX9',asset:'Travis Scott Reverse Mocha',ref:'lst_10871',corr:'corr_item_77104',amount:0,rail:'Internal',status:'Active',fee:0,note:'Fixed price removed; item remains offer-only.'},
{id:'evt_28',mins:61,type:'Stock position transferred',category:'Stocks',user:'usr_01HZYQ',counterparty:'0x91a…812e',asset:'TSLA · full position',ref:'xfr_stk_190',corr:'corr_stockxfer_190',amount:521.37,rail:'On-chain',status:'Confirmed',fee:.0091,note:'All TSLA lots moved as one user-facing position.'},
{id:'evt_29',mins:73,type:'Withdrawal initiated',category:'Funding',user:'usr_01HZX2',asset:'Cash balance',ref:'wd_22019',corr:'corr_withdraw_22019',amount:-320,rail:'Cash',status:'Processing',fee:.20,note:'Whitelisted destination and network captured.'},
{id:'evt_30',mins:74,type:'Withdrawal processor fee',category:'Fees',user:'usr_01HZX2',asset:'Cash withdrawal',ref:'fee_wd_22019',corr:'corr_withdraw_22019',amount:0,rail:'Cash',status:'Confirmed',fee:.20,note:'Payment/withdrawal cost tracked separately from principal.'},
{id:'evt_31',mins:92,type:'On-chain transaction failed',category:'Fees',user:'usr_01HZZ4',asset:'Marketplace custody transfer',ref:'0x7c91a',corr:'corr_failed_7c91a',amount:0,rail:'On-chain',status:'Failed',fee:.0023,note:'Failed business action still incurred network cost.'},
{id:'evt_32',mins:110,type:'Shipping requested',category:'Shipping',user:'usr_01HZX9',asset:'Jordan 4 Military Blue',ref:'ship_8e13',corr:'corr_ship_8e13',amount:24.95,rail:'Cash',status:'Confirmed',fee:0,note:'User requested physical redemption and accepted shipping quote.'},
{id:'evt_33',mins:111,type:'Shipping collected',category:'Treasury',user:'usr_01HZX9',asset:'Jordan 4 Military Blue',ref:'ship_8e13',corr:'corr_ship_8e13',amount:24.95,rail:'Cash',status:'Confirmed',fee:0,note:'Shipping inflow recorded separately from shipping expense.'},
{id:'evt_34',mins:112,type:'Item redemption cost',category:'Treasury',user:'usr_01HZX9',asset:'Jordan 4 Military Blue',ref:'claim_8e13',corr:'corr_ship_8e13',amount:-280,rail:'USDC',status:'Confirmed',fee:0,note:'Actual supplier/item cost basis became a real company outflow.'},
{id:'evt_35',mins:113,type:'Carrier label purchased',category:'Shipping',user:'usr_01HZX9',asset:'UPS label',ref:'label_8e13',corr:'corr_ship_8e13',amount:-18.40,rail:'Cash',status:'Confirmed',fee:0,note:'Carrier and handling expense recorded separately.'},
{id:'evt_36',mins:130,type:'Referral reward claimed',category:'Rewards',user:'usr_01J001',asset:'Referral earnings',ref:'refclaim_1033',corr:'corr_ref_1033',amount:333,rail:'Credits',status:'Confirmed',fee:0,note:'User elected Credits payout for referral claim.'},
{id:'evt_37',mins:145,type:'Lulu burned',category:'Rewards',user:'usr_01J001',asset:'Lulu #26, #27, #28',ref:'0xa1bbfa767',corr:'corr_lulu_a1bb',amount:-3,rail:'On-chain',status:'Confirmed',fee:.0009,note:'Three Lulu NFTs burned.'},
{id:'evt_38',mins:145,type:'Lulu Credits emitted',category:'Rewards',user:'usr_01J001',asset:'3 Lulu burn',ref:'emit_a1bb',corr:'corr_lulu_a1bb',amount:333,rail:'Credits',status:'Confirmed',fee:0,note:'333 Credits emitted, including 33-credit triple bonus.'},
{id:'evt_39',mins:165,type:'Earn task submitted',category:'Rewards',user:'usr_01HZYA',asset:'Post a clip',ref:'task_clip_281',corr:'corr_task_281',amount:0,rail:'Internal',status:'Submitted',fee:0,note:'Proof link submitted for manual review.'},
{id:'evt_40',mins:190,type:'Reconciliation mismatch',category:'Reconciliation',user:null,asset:'USDC wallet 0x41a…d91',ref:'recon_8b7c11',corr:'corr_recon_8b7c11',amount:-5,rail:'USDC',status:'Mismatch',fee:0,note:'Observed wallet differs from internal ledger by $5.'},
{id:'evt_41',mins:240,type:'Admin balance adjustment',category:'Admin',user:'usr_01HZZ4',asset:'Credits balance',ref:'adj_2201',corr:'corr_admin_2201',amount:25,rail:'Credits',status:'Confirmed',fee:0,note:'Manual adjustment with operator reason and audit record.'},
{id:'evt_42',mins:300,type:'Vault liquidation quote updated',category:'Vault',user:'usr_01HZX2',asset:'Nike SB Dunk Jarritos',ref:'liq_77233',corr:'corr_item_77233',amount:340.20,rail:'Internal',status:'Active',fee:0,note:'365-day option = 70% × min(initial FMV, live FMV).'},
{id:'evt_43',mins:360,type:'Auto Credit Back executed',category:'Rewards',user:'usr_01HZYA',asset:'Expired vault item',ref:'autocb_6002',corr:'corr_item_6002',amount:56,rail:'Credits',status:'Confirmed',fee:0,note:'Expired unresolved item removed from vault and settled in Credits.'},
{id:'evt_44',mins:420,type:'Public profile viewed',category:'Analytics',user:'usr_01HZX2',asset:'@maya profile',ref:'ana_profile_88',corr:'corr_analytics_88',amount:0,rail:'Internal',status:'Recorded',fee:0,note:'Analytics-only event; hidden from financial reporting.'}
];

const purchases=[
{id:'pur_72119',mins:5,user:'usr_01HZYA',product:'Streetwear 100',kind:'Streetwear',qty:1,entry:100,rail:'USDC',bonus:5,xp:100,payment:'0x93a…120f',reveal:'rev_55102',corr:'corr_crate_72119',status:'Settled'},
{id:'pur_72118',mins:10,user:'usr_01HZX9',product:'Equity Pack 50',kind:'Stocks',qty:1,entry:50,rail:'Cash',bonus:2.5,xp:50,payment:'pi_3Q91…z8H',reveal:'rev_55101',corr:'corr_stockpack_72118',status:'Settled'},
{id:'pur_72117',mins:25,user:'usr_01HZX2',product:'Sneaker 100',kind:'Sneakers',qty:3,entry:300,rail:'Cash',bonus:15,xp:300,payment:'pi_3Q90…mF2',reveal:'rev_55100',corr:'corr_crate_72117',status:'Settled'},
{id:'pur_72116',mins:22,user:'usr_01HZZ4',product:'Equity Pack 100',kind:'Stocks',qty:1,entry:100,rail:'Cash',bonus:5,xp:100,payment:'pi_3Q8y…jC7',reveal:'rev_55099',corr:'corr_stockpack_72116',status:'Review'},
{id:'pur_72115',mins:28,user:'usr_01J001',product:'Streetwear 50',kind:'Streetwear',qty:1,entry:50,rail:'USDC',bonus:2.5,xp:50,payment:'0x881…19ce',reveal:'rev_55098',corr:'corr_crate_72115',status:'Settled'},
{id:'pur_72114',mins:39,user:'usr_01HZYQ',product:'Sneaker 250',kind:'Sneakers',qty:1,entry:250,rail:'Cash',bonus:12.5,xp:250,payment:'pi_3Q8u…pL4',reveal:'rev_55097',corr:'corr_crate_72114',status:'Settled'},
{id:'pur_72113',mins:95,user:'usr_01HZX9',product:'Sneaker 100',kind:'Sneakers',qty:1,entry:100,rail:'USDC',bonus:5,xp:100,payment:'0x71b…c398',reveal:'rev_55096',corr:'corr_crate_72113',status:'Settled'},
{id:'pur_72112',mins:125,user:'usr_01HZYA',product:'Streetwear 100',kind:'Streetwear',qty:1,entry:100,rail:'Credits',bonus:5,xp:100,payment:'cr_1319',reveal:'rev_55095',corr:'corr_crate_72112',status:'Settled'},
{id:'pur_72111',mins:145,user:'usr_01J001',product:'Sneaker 100',kind:'Sneakers',qty:8,entry:800,rail:'Cash',bonus:40,xp:800,payment:'pi_3Q8j…sN3',reveal:'rev_55094',corr:'corr_crate_72111',status:'Settled'}
];

const reveals=[
{id:'rev_55102',mins:7,user:'usr_01HZYA',pack:'Streetwear 100',outcome:'Supreme Box Logo Tee',rarity:'Rare',fmv:128,decision:'Vault',fair:'Verified',flags:'—',status:'Complete',commit:'0xd21b5e47f81d5f6a9c',hash:'0xa9d33c882791b027ef',corr:'corr_crate_72119',note:'USDC-funded item kept in vault; original rail preserved.'},
{id:'rev_55101',mins:11,user:'usr_01HZX9',pack:'Equity Pack 50',outcome:'AAPL · 0.209 sh',rarity:'Uncommon',fmv:49.86,decision:'Hold stock',fair:'Verified',flags:'—',status:'Complete',commit:'0x14ab8729f2b06a7711',hash:'0x33ac1041decb859fa2',corr:'corr_stockpack_72118',note:'Stock buy and lot assignment followed reveal.'},
{id:'rev_55100',mins:27,user:'usr_01HZX2',pack:'Sneaker 100 · batch 1/3',outcome:'Nike SB Dunk Jarritos',rarity:'Epic',fmv:486,decision:'Vault',fair:'Verified',flags:'Duplicate reroll',status:'Complete',commit:'0x997e11f3c17d01aa42',hash:'0x0f7cd82a8129cba314',corr:'corr_crate_72117',note:'Duplicate prevention rerolled one locked outcome before commit.'},
{id:'rev_55099',mins:22,user:'usr_01HZZ4',pack:'Equity Pack 100',outcome:'Quote refresh required',rarity:'—',fmv:0,decision:'Pending',fair:'Review',flags:'Stale quote',status:'Exception',commit:'0x51c71e64a0e2dd7720',hash:'pending',corr:'corr_stockpack_72116',note:'FMV timestamp exceeded configured freshness threshold.'},
{id:'rev_55098',mins:29,user:'usr_01J001',pack:'Streetwear 50',outcome:'Cashback',rarity:'Common',fmv:39.5,decision:'USDC cashback',fair:'Verified',flags:'—',status:'Complete',commit:'0x229adfa8155dd8b5c2',hash:'0x57ff997c81d57d920a',corr:'corr_crate_72115',note:'Same-rail USDC settlement.'},
{id:'rev_55097',mins:41,user:'usr_01HZYQ',pack:'Sneaker 250',outcome:'Air Jordan 1 Chicago',rarity:'Rare',fmv:430,decision:'List',fair:'Verified',flags:'Pity trigger',status:'Complete',commit:'0xe3f0a861bcf116212a',hash:'0x7ab2ea31ed9fe41a67',corr:'corr_crate_72114',note:'Rare pity protection was triggered and logged.'},
{id:'rev_55096',mins:97,user:'usr_01HZX9',pack:'Sneaker 100',outcome:'Cashback',rarity:'Common',fmv:82,decision:'USDC cashback',fair:'Verified',flags:'—',status:'Complete',commit:'0xb4310ae9da01c7c384',hash:'0x44bdcaff72a1fb1c77',corr:'corr_crate_72113',note:'Original entry rail remains USDC.'},
{id:'rev_55095',mins:127,user:'usr_01HZYA',pack:'Streetwear 100',outcome:'Vintage tee',rarity:'Common',fmv:80,decision:'Credit Back',fair:'Verified',flags:'—',status:'Complete',commit:'0xca92d27c312',hash:'0xa33dde9c112',corr:'corr_crate_72112',note:'Credits-funded result settled as 64 Credit Back (80% of $80 FMV).'}
];

const marketEvents=[
{mins:2,action:'Offer accepted',kind:'Offer',item:'Air Jordan 1 Chicago',actor:'usr_01HZYQ',counter:'usr_01HZX2',value:412,fee:4.12,status:'Settling',corr:'corr_sale_11983',ref:'off_11983'},
{mins:4,action:'Ownership transferred',kind:'Transfer',item:'Air Jordan 1 Chicago',actor:'usr_01HZX2',counter:'usr_01HZYQ',value:430,fee:0,status:'Owned',corr:'corr_sale_11983',ref:'itm_00921'},
{mins:17,action:'Offer sent',kind:'Offer',item:'Air Jordan 1 Chicago',actor:'usr_01HZX2',counter:'usr_01HZYQ',value:395,fee:0,status:'Open',corr:'corr_offer_11982',ref:'off_11982'},
{mins:34,action:'Offer declined',kind:'Offer',item:'Nike SB Dunk Jarritos',actor:'usr_01HZYQ',counter:'usr_01HZX9',value:460,fee:0,status:'Closed',corr:'corr_offer_11977',ref:'off_11977'},
{mins:46,action:'Listing created',kind:'Listing',item:'Nike SB Dunk Jarritos',actor:'usr_01HZX2',counter:'—',value:510,fee:0,status:'Active',corr:'corr_item_77233',ref:'lst_10892'},
{mins:52,action:'Price removed · offer-only',kind:'Listing',item:'Travis Scott Reverse Mocha',actor:'usr_01HZX9',counter:'—',value:0,fee:0,status:'Active',corr:'corr_item_77104',ref:'lst_10871'},
{mins:96,action:'Counter offer sent',kind:'Offer',item:'Supreme MM6 Hoodie',actor:'usr_01J001',counter:'usr_01HZX2',value:286,fee:0,status:'Open',corr:'corr_offer_11891',ref:'off_11891'},
{mins:150,action:'Buy Now completed',kind:'Sale',item:'New Balance 9060',actor:'usr_01HZX9',counter:'usr_01HZYA',value:655,fee:6.55,status:'Settled',corr:'corr_sale_11811',ref:'sale_11811'},
{mins:151,action:'Listing closed',kind:'Listing',item:'New Balance 9060',actor:'usr_01HZYA',counter:'usr_01HZX9',value:655,fee:0,status:'Closed',corr:'corr_sale_11811',ref:'lst_10718'}
];

const walletEvents=[
{mins:9,action:'USDC deposit confirmed',user:'usr_01HZYA',rail:'USDC',provider:'Base',amount:500,fee:.0008,ref:'0xdep991',status:'Confirmed'},
{mins:18,action:'Cash card deposit',user:'usr_01HZX2',rail:'Cash',provider:'Card',amount:750,fee:18.35,ref:'pi_9901',status:'Confirmed'},
{mins:73,action:'Withdrawal initiated',user:'usr_01HZX2',rail:'Cash',provider:'Robinhood Chain',amount:-320,fee:.20,ref:'wd_22019',status:'Processing'},
{mins:74,action:'Withdrawal address whitelisted',user:'usr_01HZX2',rail:'Internal',provider:'Robinhood Chain',amount:0,fee:0,ref:'wl_9181',status:'Confirmed'},
{mins:80,action:'USDC withdrawal confirmed',user:'usr_01HZZ4',rail:'USDC',provider:'Solana',amount:-200,fee:.004,ref:'0xwd881',status:'Confirmed'},
{mins:121,action:'Apple Pay deposit',user:'usr_01HZYQ',rail:'Cash',provider:'Apple Pay',amount:1000,fee:25,ref:'pi_ap_771',status:'Confirmed'},
{mins:190,action:'Deposit failed',user:'usr_01J001',rail:'Cash',provider:'Card',amount:500,fee:0,ref:'pi_fail_72',status:'Failed'},
{mins:230,action:'USDC deposit detected',user:'usr_01HZX9',rail:'USDC',provider:'Ethereum',amount:1200,fee:.43,ref:'0xdep_eth_82',status:'Pending'}
];

const fees=[
{mins:0,action:'Stock sell execution',user:'usr_01HZX9',network:'Robinhood Chain',notional:31.74,cost:.0128,userFee:.20,recovered:.0128,status:'Confirmed',ref:'0xstk8821',corr:'corr_stock_8821'},
{mins:20,action:'Item transfer',user:'usr_01J001',network:'Robinhood Chain',notional:220,cost:.0011,userFee:.05,recovered:.0011,status:'Confirmed',ref:'0xtransfer221',corr:'corr_transfer_221'},
{mins:30,action:'USDC cashback settlement',user:'usr_01HZZ4',network:'Base',notional:39.50,cost:.0007,userFee:.01,recovered:.0007,status:'Confirmed',ref:'0xcb9328',corr:'corr_crate_72115'},
{mins:61,action:'Stock position transfer',user:'usr_01HZYQ',network:'Robinhood Chain',notional:521.37,cost:.0091,userFee:.10,recovered:.0091,status:'Confirmed',ref:'0xstx190',corr:'corr_stockxfer_190'},
{mins:74,action:'Cash withdrawal',user:'usr_01HZX2',network:'Processor',notional:320,cost:.20,userFee:.25,recovered:.20,status:'Confirmed',ref:'wd_22019',corr:'corr_withdraw_22019'},
{mins:92,action:'Failed custody transfer',user:'usr_01HZZ4',network:'Robinhood Chain',notional:460,cost:.0023,userFee:0,recovered:0,status:'Failed',ref:'0x7c91a',corr:'corr_failed_7c91a'},
{mins:145,action:'Lulu burn',user:'usr_01J001',network:'Ethereum',notional:0,cost:.0009,userFee:.001,recovered:.0009,status:'Confirmed',ref:'0xa1bbfa767',corr:'corr_lulu_a1bb'},
{mins:230,action:'USDC deposit',user:'usr_01HZX9',network:'Ethereum',notional:1200,cost:.43,userFee:.50,recovered:.43,status:'Pending',ref:'0xdep_eth_82',corr:'corr_dep_eth_82'}
];

const rewardEvents=[
{mins:5,event:'Crate Bonus',user:'usr_01HZYA',dir:'In',amount:5,balance:1319,ref:'bonus_72119',status:'Confirmed'},
{mins:65,event:'Credit Spend',user:'usr_01HZYQ',dir:'Out',amount:100,balance:850,ref:'pur_credit_991',status:'Confirmed'},
{mins:66,event:'Credit Back',user:'usr_01HZYQ',dir:'In',amount:64,balance:914,ref:'cb_credit_991',status:'Confirmed'},
{mins:67,event:'Crate Bonus',user:'usr_01HZYQ',dir:'In',amount:5,balance:919,ref:'bonus_991',status:'Confirmed'},
{mins:130,event:'Referral claim · Credits',user:'usr_01J001',dir:'In',amount:333,balance:2033,ref:'refclaim_1033',status:'Confirmed'},
{mins:145,event:'Lulu emission',user:'usr_01J001',dir:'In',amount:333,balance:2366,ref:'emit_a1bb',status:'Confirmed'},
{mins:165,event:'Earn task submitted',user:'usr_01HZYA',dir:'—',amount:0,balance:1319,ref:'task_clip_281',status:'Submitted'},
{mins:180,event:'X verification approved',user:'usr_01HZX2',dir:'In',amount:10,balance:430,ref:'task_x_182',status:'Approved'},
{mins:210,event:'Weekly raffle qualified',user:'usr_01HZX9',dir:'—',amount:0,balance:4915,ref:'raffle_w37',status:'Qualified'},
{mins:300,event:'Promotional Credits',user:'usr_01HZZ4',dir:'In',amount:250,balance:620,ref:'promo_sep12',status:'Confirmed'},
{mins:360,event:'Auto Credit Back',user:'usr_01HZYA',dir:'In',amount:56,balance:1375,ref:'autocb_6002',status:'Confirmed'}
];

const recon=[
{mins:1,scope:'Cash ledger totals',internal:'$4,053.25',observed:'$4,053.25',diff:'$0.00',severity:'Info',result:'Matched',ref:'cash_ledger'},
{mins:1,scope:'USDC wallet · 0x41a…d91',internal:'$18,300.00',observed:'$18,295.00',diff:'-$5.00',severity:'High',result:'Mismatch',ref:'recon_8b7c11'},
{mins:1,scope:'Credits balance · usr_01HZYA',internal:'1,319 cr',observed:'1,319 cr',diff:'0 cr',severity:'Info',result:'Matched',ref:'usr_01HZYA'},
{mins:1,scope:'Pending vault register',internal:'15 items',observed:'15 items',diff:'0',severity:'Info',result:'Matched',ref:'vault_items'},
{mins:1,scope:'Stock custody · provider',internal:'$2,914.40',observed:'$2,914.40',diff:'$0.00',severity:'Info',result:'Matched',ref:'stock_custody'},
{mins:1,scope:'Marketplace unsettled sales',internal:'1 sale',observed:'1 sale',diff:'0',severity:'Info',result:'Matched',ref:'market_unsettled'},
{mins:1,scope:'Failed on-chain transactions',internal:'1 fee event',observed:'1 fee event',diff:'0',severity:'Medium',result:'Matched',ref:'failed_tx'},
{mins:1,scope:'Reveal quote freshness',internal:'1 paused reveal',observed:'1 stale quote',diff:'0',severity:'Medium',result:'Matched',ref:'quote_freshness'}
];

const eventCatalog=[];
const addEvents=(domain,level,names,desc)=>names.forEach(name=>eventCatalog.push({domain,level,name,description:desc||`Track ${name.toLowerCase()} with user, timestamp, references and correlation ID.`}));
addEvents('Wallet & Funding','Financial',['Cash deposit initiated','Cash deposit completed','Cash deposit failed','USDC deposit detected','USDC deposit confirmed','USDC deposit failed','Card deposit completed','Apple Pay deposit completed','Withdrawal address whitelisted','Withdrawal initiated','Withdrawal processing','Withdrawal confirmed','Withdrawal failed','Cash balance credited','Cash balance debited','USDC balance credited','USDC balance debited','Credits balance credited','Credits balance debited','Manual balance adjustment','Deposit network fee','Withdrawal network fee','Payment processing fee'],'Track funding rail, provider/network, balance impact and external reference.');
addEvents('Purchases','Financial',['Crate purchase initiated','Crate purchase confirmed','Crate purchase failed','Cash crate purchase','USDC crate purchase','Credits crate purchase','Stock pack purchased','Batch purchase created','Credits spent','Cash deducted','USDC deducted','Crate Bonus issued','XP awarded','Lifetime volume updated','Insufficient balance attempt'],'Preserve original funding rail and link purchase to every downstream reveal.');
addEvents('Reveal Monitor','Operational',['Opening started','Outcomes generated','Pity system triggered','Duplicate reroll triggered','Fairness commitment created','Crate selected','Prize revealed','Rarity recorded','Reveal FMV captured','Multiplier recorded','Fairness verification passed','Fairness verification failed','Reveal exception','Price quote stale','Reveal interrupted','Batch advanced'],'Every randomization and verification state should be auditable.');
addEvents('Prize Settlement','Financial',['Cash Out selected','Keep selected','Cash Cashback issued','USDC Cashback issued','Credit Back issued','Stock assigned to portfolio','Item assigned to vault','Settlement initiated','Settlement confirmed','Settlement failed','Original prize FMV stored','Live FMV captured','Original funding rail attached'],'Separate user choice from the financial/ownership consequence.');
addEvents('Vault','Operational',['Item entered vault','Ownership created','365-day clock started','Pending liquidation quote updated','Item listed','Item repriced','Listing price removed','Platform buyout accepted','Vault cashout completed','Physical redemption requested','Item sent to user','Item received from user','Vault item expired','Auto Credit Back executed','Item removed from vault'],'Vault lifecycle must retain initial FMV, live FMV, funding rail and 365-day state.');
addEvents('Marketplace','Operational',['Offer-only inventory created','Listing created','Listing repriced','Listing price removed','Listing cancelled','Listing closed','Offer sent','Offer received','Offer countered','Counter received','Offer accepted','Offer declined','Offer cancelled','Offer expired','Buy Now initiated','Buy Now completed','Marketplace sale completed','Buyer funds debited','Seller proceeds credited','Marketplace fee charged','Ownership transferred','Marketplace settlement failed','Marketplace settlement reversed'],'One sale should appear as a correlated chain rather than one opaque row.');
addEvents('Stocks','Operational',['Stock outcome revealed','Stock buy order submitted','Stock buy partially filled','Stock buy filled','Stock buy failed','Acquisition price captured','Shares acquired','Stock lot assigned','Position consolidated','Portfolio value updated','Unrealized P&L updated','Partial sale requested','Full sale requested','Stock sell submitted','Stock sell partially filled','Stock sell filled','Stock sell failed','Sale proceeds credited','Stock position transferred','Stock lot depleted','Stock position closed'],'Stock principal belongs to the user after assignment; Observe tracks custody plus execution lifecycle.');
addEvents('Fees','Financial',['Chain gas fee incurred','Stock buy execution fee','Stock sell execution fee','Stock transfer fee','Marketplace settlement fee','Marketplace platform fee','Deposit fee','Withdrawal fee','Card processor fee','Fee charged to user','Fee recovered from user','Unrecovered fee','Fee subsidy','Failed transaction fee'],'Compare actual cost with collected/recovered amount and net platform exposure.');
addEvents('Shipping','Financial',['Shipping requested','Shipping quote generated','Shipping paid','Shipping collected','Label purchased','Carrier cost incurred','Item pulled from inventory','Supplier cost recognized','Item redemption cost paid','Shipment dispatched','Shipment delivered','Delivery failed','Shipment returned'],'Shipping collected, carrier cost and item cost basis remain separate cash events.');
addEvents('Rewards & Credits','Operational',['Credit Spend','Credit Back','Crate Bonus','Promotional Credits','Lulu burned','Lulu Credits emitted','Auto/Expiry Credit Back','Reward task submitted','Reward task approved','Reward task rejected','Reward Credits awarded','XP earned','Rare+ streak incremented','Rare+ streak broken','Daily streak incremented','Daily streak broken','Weekly raffle qualified','Raffle entry created','Referral link copied','Referred user registered','Referral activated','Referral earnings accrued','Referral tier changed','Referral claimed as Cash','Referral claimed as Credits'],'Credits and engagement systems are user activity even when no treasury cash moves.');
addEvents('Treasury','Financial',['Crate revenue received','Marketplace fee revenue','Pool revenue allocated','Supplier liability created','Supplier invoice received','Supplier payout pending','Supplier payout paid','Physical item cost recognized','Shipping revenue','Shipping expense','Hard USDC obligation created','Hard USDC obligation resolved','Pending vault exposure created','Pending vault exposure resolved','Credits emitted','Credits burned'],'Only actual company revenue/cost belongs in treasury reporting; gross marketplace value is not revenue.');
addEvents('Reconciliation','Operational',['Wallet reconciled','Wallet mismatch','Credits mismatch','Cash mismatch','USDC mismatch','Pending item mismatch','Stock custody mismatch','Marketplace settlement mismatch','Stuck transaction','Failed transaction','Transaction retried','Transaction reversed','Orphaned transaction','Fairness mismatch','Provider API failure'],'Cross-check internal state against independent sources of truth.');
addEvents('Admin','Operational',['Manual adjustment','Admin override','Rule changed','User restriction changed','Country blacklist changed','Transaction manually resolved'],'Admin actions need operator identity, reason and before/after values.');
addEvents('Product Analytics','Analytics',['Marketplace search','Marketplace filter changed','Marketplace sort changed','Item detail viewed','Stock position viewed','Fairness proof viewed','Referral link copied','Share card downloaded','Share card shared','Username changed','Deposit address copied','Notification opened','Rewards page viewed','Public profile viewed','Theme changed','Sound changed'],'Useful behavioral telemetry; keep out of financial reports and optionally out of the default operations feed.');

const metric=(label,value,sub,cls='')=>`<article class="metric-card"><div class="metric-label">${esc(label)}</div><div class="metric-value ${cls}">${value}</div><div class="metric-sub">${sub}</div></article>`;
const tag=r=>`<span class="tag ${railClass(r)}">${esc(r)}</span>`;
const status=s=>`<span class="status ${statusTone(s)}">${esc(s)}</span>`;
const amount=v=>v===0?'—':`<span class="${v>0?'amount-positive':'amount-negative'}">${v>0?'+':''}${money(v)}</span>`;
const rowAction=(type,id)=>`<button class="row-action" data-detail="${type}" data-id="${esc(id)}" aria-label="Open details">›</button>`;

function renderActivity(){
  const total=activities.length, financial=activities.filter(a=>['Funding','Purchases','Fees','Treasury'].includes(a.category)).length, exceptions=activities.filter(a=>statusTone(a.status)==='failed').length, active=new Set(activities.filter(a=>a.user).map(a=>a.user)).size;
  document.getElementById('activityMetrics').innerHTML=metric('Events in view',num(total),'All operational + analytics events')+metric('Financial events',num(financial),'Money, credits or fees')+metric('Exceptions',num(exceptions),'Require attention',exceptions?'warning':'positive')+metric('Active users',num(active),'Users represented in current feed');
  const cat=document.getElementById('activityCategory'); if(cat.options.length===1)[...new Set(activities.map(a=>a.category))].sort().forEach(v=>cat.add(new Option(v,v)));
  const rail=document.getElementById('activityRail'); if(rail.options.length===1)[...new Set(activities.map(a=>a.rail))].sort().forEach(v=>rail.add(new Option(v,v)));
  const q=document.getElementById('activitySearch').value.toLowerCase(), c=cat.value, r=rail.value, quick=document.querySelector('#activityQuickFilters .active')?.dataset.filter||'all';
  const rows=activities.filter(a=>(c==='all'||a.category===c)&&(r==='all'||a.rail===r)&&(quick==='all'||a.category===quick)&&Object.values(a).join(' ').toLowerCase().includes(q));
  document.getElementById('activityTable').innerHTML=rows.length?rows.map(a=>`<tr data-detail="event" data-id="${a.id}"><td><span class="cell-primary">${timeAgo(a.mins)}</span><span class="cell-secondary">${stamp(a.mins)}</span></td><td><span class="cell-primary">${esc(a.type)}</span><span class="cell-secondary">${esc(a.category)}</span></td><td><span class="cell-primary">${esc(userName(a.user))}</span><span class="cell-secondary mono">${esc(a.user||'system')}</span></td><td><span class="cell-primary">${esc(a.asset)}</span><span class="cell-secondary mono">${esc(a.ref)}</span></td><td>${amount(a.amount)}</td><td>${tag(a.rail)}</td><td>${status(a.status)}</td><td class="mono">${short(a.corr)}</td><td>${rowAction('event',a.id)}</td></tr>`).join(''):`<tr><td colspan="9" class="empty-state">No events match these filters.</td></tr>`;
}
function initActivityFilters(){const host=document.getElementById('activityQuickFilters');const filters=['all','Funding','Purchases','Reveals','Vault','Marketplace','Stocks','Fees','Shipping','Rewards','Treasury','Reconciliation','Admin','Analytics'];host.innerHTML=filters.map((f,i)=>`<button class="filter-chip ${i===0?'active':''}" data-filter="${f}">${f==='all'?'All activity':f}</button>`).join('');host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;host.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderActivity()})}

function renderPurchases(){
 const volume=purchases.reduce((s,p)=>s+p.entry,0), stock=purchases.filter(p=>p.kind==='Stocks').length, batches=purchases.filter(p=>p.qty>1).length, bonus=purchases.reduce((s,p)=>s+p.bonus,0);
 document.getElementById('purchaseMetrics').innerHTML=metric('Gross entry volume',money(volume),`${purchases.length} purchase records`)+metric('Stock packs',stock,'Cash-only purchases')+metric('Batch purchases',batches,'Quantity greater than 1')+metric('Crate Bonus issued',`${num(bonus)} cr`,'Non-cash reward units');
 const by={};purchases.forEach(p=>by[p.product]=(by[p.product]||0)+p.entry);renderBars('purchaseBars',Object.entries(by).map(([k,v])=>[k,v,money(v)]));
 const q=document.getElementById('purchaseSearch').value.toLowerCase(); const rows=purchases.filter(p=>Object.values(p).join(' ').toLowerCase().includes(q));
 document.getElementById('purchaseTable').innerHTML=rows.map(p=>`<tr data-detail="purchase" data-id="${p.id}"><td><span class="cell-primary mono">${p.id}</span><span class="cell-secondary">${timeAgo(p.mins)}</span></td><td>${esc(userName(p.user))}</td><td><span class="cell-primary">${esc(p.product)}</span><span class="cell-secondary">${p.kind}</span></td><td>${p.qty}</td><td>${money(p.entry)}</td><td>${tag(p.rail)}</td><td>${num(p.bonus)} cr</td><td>${num(p.xp)}</td><td class="mono">${p.reveal}</td><td>${status(p.status)}</td><td>${rowAction('purchase',p.id)}</td></tr>`).join('');
}
function renderReveals(){
 const exceptions=reveals.filter(r=>r.status==='Exception').length, verified=reveals.filter(r=>r.fair==='Verified').length, avg=reveals.reduce((s,r)=>s+r.fmv,0)/reveals.length, kept=reveals.filter(r=>/Vault|List|Hold stock/i.test(r.decision)).length;
 document.getElementById('revealMetrics').innerHTML=metric('Verified reveals',verified,`${Math.round(verified/reveals.length*100)}% of shown reveals`,'positive')+metric('Exceptions',exceptions,'Paused or manual review','warning')+metric('Average reveal FMV',money(avg),'Snapshot at reveal')+metric('Kept / held',kept,'Moved into vault or portfolio');
 const q=document.getElementById('revealSearch').value.toLowerCase(), only=document.getElementById('onlyExceptions').classList.contains('active'); const rows=reveals.filter(r=>(!only||r.status==='Exception')&&Object.values(r).join(' ').toLowerCase().includes(q));
 document.getElementById('revealTable').innerHTML=rows.map(r=>`<tr data-detail="reveal" data-id="${r.id}"><td><span class="cell-primary mono">${r.id}</span><span class="cell-secondary">${timeAgo(r.mins)}</span></td><td>${esc(userName(r.user))}</td><td>${esc(r.pack)}</td><td><span class="cell-primary">${esc(r.outcome)}</span><span class="cell-secondary">${esc(r.rarity)}</span></td><td>${money(r.fmv)}</td><td>${esc(r.decision)}</td><td>${status(r.fair)}</td><td>${r.flags==='—'?'<span class="cell-secondary">—</span>':`<span class="status pending">${esc(r.flags)}</span>`}</td><td>${status(r.status)}</td><td>${rowAction('reveal',r.id)}</td></tr>`).join('');
}
function renderMarket(){
 const active=marketEvents.filter(e=>e.kind==='Listing'&&e.status==='Active').length, offers=marketEvents.filter(e=>e.kind==='Offer').length, sale=marketEvents.filter(e=>e.kind==='Sale'||/Seller proceeds|Buy Now/i.test(e.action)).reduce((s,e)=>s+e.value,0), feesTotal=marketEvents.reduce((s,e)=>s+e.fee,0);
 document.getElementById('marketMetrics').innerHTML=metric('Active listing events',active,'Including offer-only states')+metric('Offer events',offers,'Sent, accepted, declined, countered')+metric('Sale volume',money(sale),'Gross source volume')+metric('Platform fees',money(feesTotal),'Chosen revenue from shown sales');
 const f=document.querySelector('#marketFilter .active')?.dataset.filter||'all';const rows=marketEvents.filter(e=>f==='all'||e.kind===f);document.getElementById('marketTable').innerHTML=rows.map((e,i)=>`<tr data-detail="market" data-id="${i}"><td>${timeAgo(e.mins)}</td><td><span class="cell-primary">${e.action}</span><span class="cell-secondary">${e.kind}</span></td><td>${e.item}</td><td>${esc(userName(e.actor))}</td><td>${esc(userName(e.counter))}</td><td>${e.value?money(e.value):'—'}</td><td>${e.fee?money(e.fee):'—'}</td><td>${status(e.status)}</td><td class="mono">${short(e.corr)}</td><td>${rowAction('market',i)}</td></tr>`).join('');
}
function renderPortfolios(){
 const stock=users.reduce((s,u)=>s+u.stocks,0), vault=users.reduce((s,u)=>s+u.vaultValue,0), basis=users.reduce((s,u)=>s+u.stockCost,0), pnl=stock-basis, pending=users.reduce((s,u)=>s+u.pending,0);
 document.getElementById('portfolioMetrics').innerHTML=metric('Stock value',money(stock),'User-owned positions')+metric('Unrealized stock P&L',money(pnl),'Value minus acquisition basis',pnl>=0?'positive':'negative')+metric('Vault market value',money(vault),'Physical collectible holdings')+metric('Pending vault exposure',money(pending),'70% capped liquidation planning exposure');
 const q=document.getElementById('portfolioSearch').value.toLowerCase(); const rows=users.filter(u=>Object.values(u).join(' ').toLowerCase().includes(q));document.getElementById('portfolioGrid').innerHTML=rows.map(u=>{const total=u.cash+u.usdc+u.stocks+u.vaultValue;return `<article class="portfolio-card" data-detail="user" data-id="${u.id}"><div class="user-row"><div class="user-avatar">${initials(u.name)}</div><div class="user-meta"><strong>${u.name}</strong><span>${u.handle} · ${u.id}</span></div><div class="user-total"><strong>${money(total)}</strong><span>tracked value</span></div></div><div class="portfolio-mini-grid"><div class="mini-balance"><span>Cash</span><strong>${money(u.cash)}</strong></div><div class="mini-balance"><span>USDC</span><strong>${money(u.usdc)}</strong></div><div class="mini-balance"><span>Credits</span><strong>${num(u.credits)} cr</strong></div><div class="mini-balance"><span>Stocks</span><strong>${money(u.stocks)}</strong></div><div class="mini-balance"><span>Vault</span><strong>${money(u.vaultValue)}</strong></div><div class="mini-balance"><span>Pending exposure</span><strong>${money(u.pending)}</strong></div></div></article>`}).join('');
}
function renderWallets(){
 const totalCash=users.reduce((s,u)=>s+u.cash,0), totalUsdc=users.reduce((s,u)=>s+u.usdc,0), deposits=walletEvents.filter(e=>e.amount>0&&/deposit/i.test(e.action)).reduce((s,e)=>s+e.amount,0), withdrawals=Math.abs(walletEvents.filter(e=>e.amount<0).reduce((s,e)=>s+e.amount,0)), failures=walletEvents.filter(e=>statusTone(e.status)==='failed').length;
 document.getElementById('walletMetrics').innerHTML=metric('User Cash balances',money(totalCash),'Tracked account cash')+metric('User USDC balances',money(totalUsdc),'Tracked stablecoin balances')+metric('Deposits shown',money(deposits),'Gross successful/pending deposit intents')+metric('Withdrawal volume',money(withdrawals),`${failures} failed payment event${failures===1?'':'s'}`);
 renderBars('walletBars',[['Cash movement',walletEvents.filter(x=>x.rail==='Cash').reduce((s,x)=>s+Math.abs(x.amount),0),'Cash'],['USDC movement',walletEvents.filter(x=>x.rail==='USDC').reduce((s,x)=>s+Math.abs(x.amount),0),'USDC'],['Fees',walletEvents.reduce((s,x)=>s+x.fee,0),'Actual fees']]);
 const q=document.getElementById('walletSearch').value.toLowerCase();document.getElementById('walletTable').innerHTML=walletEvents.filter(e=>Object.values(e).join(' ').toLowerCase().includes(q)).map((e,i)=>`<tr data-detail="wallet" data-id="${i}"><td>${timeAgo(e.mins)}</td><td>${e.action}</td><td>${userName(e.user)}</td><td>${tag(e.rail)}</td><td>${e.provider}</td><td>${amount(e.amount)}</td><td>${e.fee?money(e.fee):'—'}</td><td class="mono">${short(e.ref)}</td><td>${status(e.status)}</td><td>${rowAction('wallet',i)}</td></tr>`).join('');
}
function renderFees(){
 const cost=fees.reduce((s,f)=>s+f.cost,0), collected=fees.reduce((s,f)=>s+f.userFee,0), recovered=fees.reduce((s,f)=>s+f.recovered,0), exposure=Math.max(0,cost-recovered), coverage=cost?recovered/cost*100:100;
 document.getElementById('feeMetrics').innerHTML=metric('Actual transaction cost',money(cost,4),'Successful + failed')+metric('Fees charged to users',money(collected,4),'Configured fee amount')+metric('Cost recovered',money(recovered,4),`${pct(coverage)} of actual cost`,'positive')+metric('Net platform exposure',money(exposure,4),'Actual cost not recovered',exposure?'warning':'positive');
 const by={};fees.forEach(f=>by[f.network]=(by[f.network]||0)+f.cost);renderBars('feeNetworkBars',Object.entries(by).map(([k,v])=>[k,v,money(v,4)]));document.getElementById('coveragePct').textContent=pct(coverage);document.getElementById('coverageRing').style.setProperty('--pct',`${Math.min(360,coverage*3.6)}deg`);document.getElementById('coverageRecovered').textContent=`${money(recovered,4)} recovered`;document.getElementById('coverageExposure').textContent=`${money(exposure,4)} net platform exposure`;
 const q=document.getElementById('feeSearch').value.toLowerCase();document.getElementById('feeTable').innerHTML=fees.filter(f=>Object.values(f).join(' ').toLowerCase().includes(q)).map((f,i)=>{const net=Math.max(0,f.cost-f.recovered);return `<tr data-detail="fee" data-id="${i}"><td>${timeAgo(f.mins)}</td><td>${f.action}</td><td>${userName(f.user)}</td><td>${f.network}</td><td>${money(f.notional)}</td><td>${money(f.cost,4)}</td><td>${money(f.userFee,4)}</td><td>${money(f.recovered,4)}</td><td class="${net?'amount-negative':'amount-positive'}">${money(net,4)}</td><td>${status(f.status)}</td><td>${rowAction('fee',i)}</td></tr>`}).join('');
}
function renderRewards(){
 const circulation=users.reduce((s,u)=>s+u.credits,0), spend=rewardEvents.filter(e=>e.dir==='Out').reduce((s,e)=>s+e.amount,0), back=rewardEvents.filter(e=>/Credit Back/i.test(e.event)).reduce((s,e)=>s+e.amount,0), emissions=rewardEvents.filter(e=>e.dir==='In'&&!/Credit Back/i.test(e.event)).reduce((s,e)=>s+e.amount,0);
 document.getElementById('rewardMetrics').innerHTML=metric('Credits in shown accounts',`${num(circulation)} cr`,'Non-cash units')+metric('Credit Spend',`${num(spend)} cr`,'Credits removed')+metric('Credit Back',`${num(back)} cr`,'Outcome settlement')+metric('New emissions',`${num(emissions)} cr`,'Bonus, referral, Lulu, promos, tasks');
 const types={};rewardEvents.forEach(e=>types[e.event]=(types[e.event]||0)+e.amount);renderBars('rewardBars',Object.entries(types).filter(([,v])=>v>0).map(([k,v])=>[k,v,`${num(v)} cr`]));
 const q=document.getElementById('rewardSearch').value.toLowerCase();document.getElementById('rewardTable').innerHTML=rewardEvents.filter(e=>Object.values(e).join(' ').toLowerCase().includes(q)).map((e,i)=>`<tr data-detail="reward" data-id="${i}"><td>${timeAgo(e.mins)}</td><td>${e.event}</td><td>${userName(e.user)}</td><td>${e.dir}</td><td>${e.amount?`${e.dir==='Out'?'-':'+'}${num(e.amount)} cr`:'—'}</td><td>${num(e.balance)} cr</td><td class="mono">${e.ref}</td><td>${status(e.status)}</td><td>${rowAction('reward',i)}</td></tr>`).join('');
}
function renderRecon(){
 const mismatch=recon.filter(r=>r.result==='Mismatch').length, high=recon.filter(r=>r.severity==='High').length, matched=recon.filter(r=>r.result==='Matched').length;
 document.getElementById('reconMetrics').innerHTML=metric('Checks run',recon.length,'Across core sources of truth')+metric('Matched',matched,'No difference','positive')+metric('Mismatches',mismatch,'Require investigation',mismatch?'warning':'positive')+metric('High severity',high,'Immediate attention',high?'negative':'positive');
 const q=document.getElementById('reconSearch').value.toLowerCase();document.getElementById('reconTable').innerHTML=recon.filter(r=>Object.values(r).join(' ').toLowerCase().includes(q)).map((r,i)=>`<tr data-detail="recon" data-id="${i}"><td>${timeAgo(r.mins)}</td><td>${r.scope}</td><td>${r.internal}</td><td>${r.observed}</td><td>${r.diff}</td><td>${r.severity}</td><td>${status(r.result)}</td><td class="mono">${r.ref}</td><td>${rowAction('recon',i)}</td></tr>`).join('');
}
function renderCatalog(){
 const domain=document.getElementById('catalogDomain');if(domain.options.length===1)[...new Set(eventCatalog.map(e=>e.domain))].sort().forEach(v=>domain.add(new Option(v,v)));const q=document.getElementById('catalogSearch').value.toLowerCase(),d=domain.value,l=document.getElementById('catalogLevel').value;const rows=eventCatalog.filter(e=>(d==='all'||e.domain===d)&&(l==='all'||e.level===l)&&Object.values(e).join(' ').toLowerCase().includes(q));document.getElementById('catalogCount').textContent=`${rows.length} of ${eventCatalog.length} event types`;document.getElementById('catalogGrid').innerHTML=rows.map(e=>`<article class="catalog-card"><div class="catalog-card-head"><span class="catalog-domain">${e.domain}</span><span class="status level-${e.level.toLowerCase()}">${e.level}</span></div><h3>${e.name}</h3><p>${e.description}</p><div class="catalog-meta"><span class="tag internal">correlation_id</span><span class="tag internal">user_id</span><span class="tag internal">reference</span></div></article>`).join('');
}
function renderBars(id,rows){const max=Math.max(1,...rows.map(r=>r[1]));document.getElementById(id).innerHTML=rows.sort((a,b)=>b[1]-a[1]).map(r=>`<div class="bar-row"><div class="bar-label"><strong>${esc(r[0])}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(2,r[1]/max*100)}%"></div></div><div class="bar-value">${esc(r[2])}</div></div>`).join('')}
const initials=n=>n.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();

function openDrawer(type,id){
 let title='Details',eyebrow=type.toUpperCase(),body='';
 if(type==='event'){const a=activities.find(x=>x.id===id);if(!a)return;title=a.type;eyebrow=a.category;body=eventDrawer(a)}
 if(type==='purchase'){const p=purchases.find(x=>x.id===id);if(!p)return;title=p.id;eyebrow='PURCHASE';body=objectDrawer(p,`Purchase · ${p.product}`,p.corr)}
 if(type==='reveal'){const r=reveals.find(x=>x.id===id);if(!r)return;title=r.id;eyebrow='REVEAL';body=objectDrawer(r,`${r.outcome} · ${r.decision}`,r.corr)}
 if(type==='market'){const e=marketEvents[Number(id)];if(!e)return;title=e.action;eyebrow='SECONDARY MARKET';body=objectDrawer(e,e.item,e.corr)}
 if(type==='wallet'){const e=walletEvents[Number(id)];if(!e)return;title=e.action;eyebrow='WALLET';body=objectDrawer(e,userName(e.user))}
 if(type==='fee'){const e=fees[Number(id)];if(!e)return;title=e.action;eyebrow='FEE';body=objectDrawer(e,`Actual cost ${money(e.cost,4)}`,e.corr)}
 if(type==='reward'){const e=rewardEvents[Number(id)];if(!e)return;title=e.event;eyebrow='REWARD';body=objectDrawer(e,userName(e.user))}
 if(type==='recon'){const e=recon[Number(id)];if(!e)return;title=e.scope;eyebrow='RECONCILIATION';body=objectDrawer(e,`${e.result} · ${e.diff}`)}
 if(type==='user'){const u=userById[id];if(!u)return;title=u.name;eyebrow='USER PORTFOLIO';body=userDrawer(u)}
 document.getElementById('drawerTitle').textContent=title;document.getElementById('drawerEyebrow').textContent=eyebrow;document.getElementById('drawerBody').innerHTML=body;document.getElementById('detailDrawer').classList.add('open');document.getElementById('drawerBackdrop').classList.add('open');document.getElementById('detailDrawer').setAttribute('aria-hidden','false');
}
function kv(k,v){return `<div class="detail-kv"><span>${esc(k)}</span><strong>${esc(v??'—')}</strong></div>`}
function eventDrawer(a){const u=userById[a.user];const related=activities.filter(x=>x.corr===a.corr).sort((x,y)=>y.mins-x.mins);return `${u?`<div class="drawer-section"><div class="drawer-user-head"><div class="user-avatar">${initials(u.name)}</div><div><strong>${u.name}</strong><span>${u.id} · ${u.wallet}</span></div></div></div>`:''}<div class="drawer-section"><div class="drawer-section-title">Event</div><div class="detail-grid">${kv('Event ID',a.id)}${kv('Category',a.category)}${kv('Reference',a.ref)}${kv('Correlation ID',a.corr)}${kv('Rail',a.rail)}${kv('Status',a.status)}${kv('Amount',a.amount?money(a.amount):'—')}${kv('Direct fee',a.fee?money(a.fee,4):'—')}</div><div class="detail-note">${esc(a.note)}</div></div>${timelineDrawer(related)}`}
function objectDrawer(o,headline,corr){const entries=Object.entries(o).filter(([k])=>!['note'].includes(k));const related=corr?activities.filter(x=>x.corr===corr).sort((a,b)=>b.mins-a.mins):[];return `<div class="drawer-section"><div class="drawer-section-title">${esc(headline)}</div><div class="detail-grid">${entries.map(([k,v])=>kv(k.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase()),typeof v==='number'&&/amount|entry|fmv|fee|value|cost|notional/i.test(k)?money(v):v)).join('')}</div>${o.note?`<div class="detail-note">${esc(o.note)}</div>`:''}</div>${related.length?timelineDrawer(related):''}`}
function timelineDrawer(rows){return `<div class="drawer-section"><div class="drawer-section-title">Correlation timeline · ${rows[0]?.corr||'—'}</div><div class="timeline">${rows.map(r=>`<div class="timeline-row"><strong>${esc(r.type)}</strong><span>${timeAgo(r.mins)} · ${esc(r.ref)} · ${esc(r.status)}</span></div>`).join('')}</div></div>`}
function userDrawer(u){const pos=positions[u.id]||[],events=activities.filter(a=>a.user===u.id).slice(0,10);return `<div class="drawer-section"><div class="drawer-user-head"><div class="user-avatar">${initials(u.name)}</div><div><strong>${u.name}</strong><span>${u.handle} · ${u.id}<br>${u.wallet}</span></div></div></div><div class="drawer-section"><div class="drawer-section-title">Balances & ownership</div><div class="detail-grid">${kv('Cash',money(u.cash))}${kv('USDC',money(u.usdc))}${kv('Credits',`${num(u.credits)} cr`)}${kv('Stocks',money(u.stocks))}${kv('Stock cost basis',money(u.stockCost))}${kv('Vault market value',money(u.vaultValue))}${kv('Inventory items',u.inventory)}${kv('Pending exposure',money(u.pending))}</div></div><div class="drawer-section"><div class="drawer-section-title">Stock positions</div>${pos.length?`<div class="timeline">${pos.map(p=>`<div class="timeline-row"><strong>${p[0]} · ${p[1]} sh · ${money(p[2])}</strong><span>Acquisition basis ${money(p[3])} · unrealized ${money(p[2]-p[3])}</span></div>`).join('')}</div>`:'<div class="detail-note">No stock positions.</div>'}</div><div class="drawer-section"><div class="drawer-section-title">Recent account activity</div><div class="timeline">${events.map(e=>`<div class="timeline-row"><strong>${e.type}</strong><span>${timeAgo(e.mins)} · ${e.ref}</span></div>`).join('')}</div></div>`}
function closeDrawer(){document.getElementById('detailDrawer').classList.remove('open');document.getElementById('drawerBackdrop').classList.remove('open');document.getElementById('detailDrawer').setAttribute('aria-hidden','true')}

const renderers={activity:renderActivity,purchases:renderPurchases,reveals:renderReveals,market:renderMarket,portfolios:renderPortfolios,wallets:renderWallets,fees:renderFees,rewards:renderRewards,recon:renderRecon,catalog:renderCatalog};
function showView(name){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));const view=document.getElementById(`view-${name}`);document.getElementById('pageTitle').textContent=view.dataset.title;document.getElementById('sectionEyebrow').textContent=view.dataset.eyebrow;renderers[name]?.();document.getElementById('sidebar').classList.remove('open');}
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function exportCurrent(){const active=document.querySelector('.view.active');const rows=[...active.querySelectorAll('table tr')].map(tr=>[...tr.querySelectorAll('th,td')].slice(0,-1).map(c=>csvEscape(c.innerText.trim())).join(','));const blob=new Blob([rows.join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`observe-${active.id.replace('view-','')}.csv`;a.click();URL.revokeObjectURL(a.href);toast('CSV exported')}
let toastTimer;function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}

function wire(){
 document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
 document.getElementById('openSidebar').addEventListener('click',()=>document.getElementById('sidebar').classList.add('open'));document.getElementById('closeSidebar').addEventListener('click',()=>document.getElementById('sidebar').classList.remove('open'));
 document.getElementById('closeDrawer').addEventListener('click',closeDrawer);document.getElementById('drawerBackdrop').addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});
 document.addEventListener('click',e=>{const x=e.target.closest('[data-detail]');if(!x)return;openDrawer(x.dataset.detail,x.dataset.id)});
 document.getElementById('exportButton').addEventListener('click',exportCurrent);
 document.getElementById('activitySearch').addEventListener('input',renderActivity);document.getElementById('activityCategory').addEventListener('change',renderActivity);document.getElementById('activityRail').addEventListener('change',renderActivity);
 document.getElementById('purchaseSearch').addEventListener('input',renderPurchases);document.getElementById('revealSearch').addEventListener('input',renderReveals);document.getElementById('onlyExceptions').addEventListener('click',e=>{e.currentTarget.classList.toggle('active');e.currentTarget.textContent=e.currentTarget.classList.contains('active')?'Show all reveals':'Show exceptions';renderReveals()});
 document.getElementById('marketFilter').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('#marketFilter button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMarket()});
 document.getElementById('portfolioSearch').addEventListener('input',renderPortfolios);document.getElementById('walletSearch').addEventListener('input',renderWallets);document.getElementById('feeSearch').addEventListener('input',renderFees);document.getElementById('rewardSearch').addEventListener('input',renderRewards);document.getElementById('reconSearch').addEventListener('input',renderRecon);document.getElementById('catalogSearch').addEventListener('input',renderCatalog);document.getElementById('catalogDomain').addEventListener('change',renderCatalog);document.getElementById('catalogLevel').addEventListener('change',renderCatalog);
 document.getElementById('runRecon').addEventListener('click',()=>{toast('Reconciliation checks completed');renderRecon()});
 const global=document.getElementById('globalSearch');global.addEventListener('keydown',e=>{if(e.key!=='Enter')return;showView('activity');document.getElementById('activitySearch').value=global.value;renderActivity()});
}

initActivityFilters();wire();Object.values(renderers).forEach(fn=>fn());document.getElementById('lastUpdated').textContent='just now';setInterval(()=>{document.getElementById('lastUpdated').textContent='just now'},15000);
